OpenZeppelin/ethernaut

- contracts/attacks/CoinFlipAttack.sol
- contracts/levels/CoinFlip.sol
- contracts/levels/CoinFlipFactory.sol
- gamedata/descriptions/levels/coinflip.md
- gamedata/descriptions/levels/coinflip_complete.md
- gamedata/gamedata.json
- test/LevelTests.js
Added a new level that demonstrates a predictable number generator. Players need to guess the outcome of a 50/50 coin flip based on the previous blockhash. Players are only allowed to flip once per block, so that they're forced to calculate multiple values rather than trying to spam one correct answer.
> Added new level: Coin Flip

- contracts/attacks/TelephoneAttack.sol
- contracts/levels/Telephone.sol
- contracts/levels/TelephoneFactory.sol
- gamedata/descriptions/levels/telephone.md
- gamedata/descriptions/levels/telephone_complete.md
- gamedata/gamedata.json
- test/LevelTests.js
I've added a new level that demonstrates the difference between `tx.origin` and `msg.sender`
> Added new level: Telephone

- gamedata/descriptions/levels/instances.md
Added a link and updated the list of supported browsers.
> instances: update metamask info

- src/middlewares/submitLevelInstance.js
- src/middlewares/syncPlayerProgress.js
They caused errors in the console.
> Removed calls to non-existing action

- contracts/attacks/PreservationAttack.sol
- contracts/levels/Preservation.sol
- contracts/levels/PreservationFactory.sol
- gamedata/descriptions/levels/preservation.md
- gamedata/descriptions/levels/preservation_complete.md
- gamedata/gamedata.json
- package-lock.json
- package.json
- test/levels/Preservation.test.js
This level teaches about the state preserving context of `delegatecall` (this particular aspect is not demonstrated in the other `delegatecall` challenge). 
It is slightly convoluted, and is this way to make it more difficult. The underlying lesson could be distilled out, but I figured I'd make a semi-difficult level. There are two instances of the library contract, to ensure that user's cannot destroy their level instance, i.e every level instance always has a solution, regardless of user input.
> New Level: Preservation

- README.md
The readme still contained a link to a deleted picture.
> Removed dead comic image references.

- contracts/levels/NaughtCoin.sol
Removed an unnecessary `if` statement that might confuse players.
> Simplified NaughtCoin

- gamedata/authors.json
> Add donation address

- gamedata/descriptions/levels/elevator_complete.md
> Add an alternative way to solve elevator level

- contracts/attacks/DenialAttack.sol
- contracts/levels/Denial.sol
- contracts/levels/DenialFactory.sol
- gamedata/descriptions/levels/denial.md
- gamedata/descriptions/levels/denial_complete.md
- gamedata/gamedata.json
- test/levels/Denial.test.js
I noticed this kind of vulnerability recently and thought a simplified version would be good as an ethernaut level. 
Let me know what you think.
> Add Denial level

- contracts/attacks/CoinFlipAttack.sol
- contracts/levels/CoinFlip.sol
- contracts/levels/Denial.sol
- contracts/levels/Fallback.sol
- contracts/levels/Fallout.sol
- contracts/levels/GatekeeperOne.sol
- contracts/levels/NaughtCoin.sol
- contracts/levels/Recovery.sol
- contracts/levels/RecoverySimpleToken.sol
- contracts/levels/Reentrance.sol
- package-lock.json
- package.json
The goal is to promote good Solidity practices using the SafeMath library to handle arithmetic operations. This PR adds version 2.1.0 of openzeppelin-solidity (the newest that doesn't make problems with compilation).
SafeMath is added in all places, where it doesn't affect level workflow.
> Use SafeMath for arithmetic operations #122

- contracts/levels/base/Level.sol
Reverts OpenZeppelin/ethernaut#125
> Revert "update openzeppelin-solidity"

- package-lock.json
- scripts/build.js
- src/utils/ethutil.js
Fix build errors on https://github.com/OpenZeppelin/ethernaut/pull/172/files
> Fix issue170 for solidity04

- gamedata/descriptions/levels/coinflip.md
I've been contacted a few times to say that the level is confusing because it is not apparent that you need to deploy a contract to solve the challenge. I've updated the hint accordingly.
> updated coinflip hint

- client/public/index.html
Adds Optinmonster embed just before </body> on index.html.
This is for marketing integration by Portia Roberts and @spalladino 
ATTN:  @xaler5
> Add Optinmonster to Index

- client/src/gamedata/cn_simplified/descriptions/levels/instances.md
- client/src/gamedata/cn_simplified/strings.json
- client/src/gamedata/en/descriptions/levels/instances.md
- client/src/gamedata/en/strings.json
- client/src/gamedata/es/descriptions/levels/instances.md
- client/src/gamedata/es/strings.json
- client/src/gamedata/ja/descriptions/levels/instances.md
- client/src/gamedata/ja/strings.json
- Add more faucets options in all languages and both in the Help page but also in the console prompt
> add more faucets

- contracts/contracts/levels/AlienCodex.sol
❤️ Loved solving this level, didn't love looking at line 21 that was misaligned from all the others because of an extra tab instead of space. ❤️
> fixed extra tab (instead of spaces) format issue

- client/src/gamedata/en/descriptions/levels/recovery_complete.md
> fixed typo

- client/src/gamedata/en/descriptions/levels/motorbike_complete.md
- client/src/gamedata/ru/descriptions/levels/motorbike_complete.md
Minor completed motorbike description typo fix.
> Fix Motorbike Completed Description Typo

- client/src/gamedata/en/descriptions/levels/doubleentrypoint.md
- client/src/gamedata/en/descriptions/levels/motorbike_complete.md
- client/src/gamedata/ru/descriptions/levels/doubleentrypoint.md
- client/src/gamedata/ru/descriptions/levels/motorbike_complete.md
Fix some of the DoubleEntryPoint's description typos.
> Fix DoubleEntryPoint Description Typos

- client/src/gamedata/es/descriptions/levels/doubleentrypoint.md
- client/src/gamedata/es/descriptions/levels/doubleentrypoint_complete.md
With love and hope that someday, nobody will need to know other language when he or she wants to learn stuff 😄
> Translates level 26 DoubleEntryPoint to spanish

- README-tr.md
Added Turkish language version of README-tr.md
> Adding Turkish Translation to README

- contracts/contracts/attacks/MagicNumSolver.sol
As correctly observed at line 10: Hex(2a) = Dec(42)
> Fix: set correct value in the comment

- client/scripts/deploy_contracts.mjs
This PR includes following:
- Checks the proxy statistics is already being set in given ethernaut contract.
> feat: check ProxyStat is already being set

- client/src/middlewares/setNetwork.js
I noticed the alert grammar needed an update so I went ahead and made a quick PR to fix it.
> 💬 Update setNetwork alert grammar

- client/src/constants.js
- client/src/gamedata/gamedata.json
- client/src/middlewares/loadLevelInstance.js
- client/src/middlewares/submitLevelInstance.js
- client/src/utils/ethutil.js
- contracts/hardhat.config.js
- contracts/package.json
- yarn.lock
1. Converting level submission to EIP 1559 for Goerli, Sepolia and Mumbai
2. Cleaned up EIP1559 gas details input to transaction
3. Changed instanceGas for the deployment of `GoodSamaritan` and `Motorbike` level after comparing it with the gas shown by hardhat gas reporter.
> Convert submit level to EIP 1559

- client/src/gamedata/en/descriptions/levels/goodsamaritan_complete.md
Give a detailed description of the level and what it taught us about custom errors in Solidity.
Also add to the congratulations, given that this is currently the final level, and link to this Github repo for folks who might want to contribute and/or propose a new level (can always be moved to another completion description when another level is added).
> Update goodsamaritan_complete.md with a detailed description of the lesson learned, akin to other completion descriptions

- client/src/styles/app.css
When screen size is less than 885px, width of box is made 100%
> Added screen resize fix

- client/src/actions/index.js
- client/src/containers/Level.js
- client/src/middlewares/loadEthernautContract.js
- client/src/middlewares/submitLevelInstance.js
- client/src/middlewares/syncPlayerProgress.js
- client/src/reducers/playerReducer.js
- client/src/utils/ethutil.js
- client/src/utils/statsContract.js
1. Level completed info of a player is now fetched from stats contract
2. Removed old code for fetching it from logs
> Fetching the levels solved by player from stats contract and showing it in the UI

- client/src/containers/App.js
- client/src/middlewares/activateLevel.js
* Some minor fixes in the add net network flow
* When level is not deployed, redirect to proper url
* Show level address only if it is deployed
> Level redirection fix

- client/src/gamedata/en/descriptions/levels/instances.md
I suggest changing the description a bit in order to make it more flexible, and specific.
> 💬 Update text

- client/src/containers/Level.js
- client/src/styles/app.css
- client/src/styles/level.css
- client/src/utils/getlevelsdata.js
Reverts OpenZeppelin/ethernaut#532
> Revert "Bug/fix dropdown and bugs"

- contracts/contracts/metrics/Statistics.sol
Average calculation update done only when player solves a level for the first time
> Average time fix

- client/src/gamedata/es/descriptions/levels/instances.md
Translate to Spanish untranslated section
> feat: translate to Spanish an untranslated section and fix typo

- client/src/containers/Stats.js
Assigning to state issue fixed
> stats-issue-fix

- client/src/containers/Header.js
- client/src/containers/Level.js
- client/src/utils/svg.js
* Added fix for issue where image is not rendered in dark mode
> added fix for dark mode light mode issue

- client/src/containers/Stats.js
- client/src/utils/statsContract.js
* Make api calls faster
* Taken care of error when user address is not passed while creating contract instance
> made calls parallel

- client/src/containers/Header.js
- client/src/styles/app.css
> change header text to icon

- client/src/components/leaderboard/Hubspot.js
- client/src/components/leaderboard/checkIfAliasExist.js
> Fixed alias submission

- client/src/gamedata/es/descriptions/levels/gatekeeper3.md
- client/src/gamedata/es/descriptions/levels/gatekeeper3_complete.md
Add Spanish translation to [Gatekeeper Three](https://ethernaut.openzeppelin.com/level/0x0b0276F85EF92432fBd6529E169D9dE4aD337b1F) level description
> Add Spanish translation

- client/src/gamedata/gamedata.json
Solves https://github.com/OpenZeppelin/ethernaut/issues/579
> Difficulty adjustments for Privacy and Gatekeeper One

- client/src/containers/Header.js
- client/src/containers/Help.js
- client/src/containers/Leaderboard.js
- client/src/containers/Level.js
- client/src/containers/Stats.js
- client/src/gamedata/ar/strings.json
- client/src/gamedata/en/strings.json
- client/src/gamedata/es/strings.json
- client/src/gamedata/fr/strings.json
- client/src/gamedata/ja/strings.json
- client/src/gamedata/pt_br/strings.json
- client/src/gamedata/ru/strings.json
- client/src/gamedata/tr/strings.json
- client/src/gamedata/zh_cn/strings.json
- client/src/gamedata/zh_tw/strings.json
- client/src/styles/app.css
Temporary banner for [Ethernaut CTF](https://ctf.openzeppelin.com/) (to be removed after event finishes)
> ✨ Add Ethernaut CTF header

- client/src/middlewares/loadEthernautContract.js
- client/src/middlewares/setNetwork.js
- client/src/utils/ethutil.js
- contracts/contracts/attacks/GatekeeperThreeAttack.sol
- contracts/contracts/factory/LocalFactory.sol
- contracts/contracts/helpers/Ownable-05.sol
1. Fix `client/src/utils/ethutil.js`   comment misspell 
2. Fix `client/src/middlewares/loadEthernautContract.js`  comment misspell 
3. Fix  `client/src/middlewares/setNetwork.js` comment misspell 
4. Fix `contracts/contracts/attacks/GatekeeperThreeAttack.sol` misspell 
5. Fix `contracts/contracts/factory/LocalFactory.sol` misspell
6. Fix `contracts/contracts/helpers/Ownable-05.sol` misspell
> Fix misspell 

- client/src/gamedata/en/descriptions/levels/magicnum_complete.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `habilities` to `abilities`
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- .github/workflows/cla.yml
- LICENSE
- Add CLA Assistant according to AGPL LICENSE policy
- Change LICENSE to AGPL
> feat: Add CLA assistant bot and Change LICENSE
