README.md, src/containers/Home.js
As `ethernaut-devcon3.zeppelin.solutions` is now no longer mantained, we're just not mentioning it here anymore.
=> Remove all references to devcon3

gamedata/gamedata.json
…rather than 200k, which was insufficient for factory contract to deploy new instances
Error tracked in issue #91 - thanks for pointing this out @ajsantander !
=> Bug fix: increased Alien contract creation instanceGas to 500k

src/constants.js, src/index.js, src/middlewares/loadEthernautContract.js, src/middlewares/setPlayerAddress.js
- This PR adds a code to prepare for Metamask changes that will happen from 2nd of November.
- The UI for Approve/Reject has not been implemented yet. Right now the account is enable by default.
- I have left in the code `mockRejection:true` as parameter in `window.ethereum.enable()` for testing the reject mode. Leave the field empty for normal approve mode.
- The code should work without problems after 2nd but it could be tested again when the UI for approve will be implemented in official version.
- I have also committed the fix for `NETWORKS.LOCAL`
Web3
I have tested the code locally on Mac OS, using the latest version of Metamask (`4.12.0`)
Fixes: #48
=> [WIP] Web3 refactor to new injection

contracts/attacks/GatekeeperOneAttack.sol
Now the attack will work when optimization is enabled *or* disabled. Good catch @ajsantander!
=> Adjust GatekeeperOne attack for optimization-disabled contract instance

src/middlewares/syncPlayerProgress.js, test/EthernautTests.js, test/utils/TestUtils.js
Hot fix for #160 
* Fixed filter on 'data' when syncing player progress
* Updated Ethernaut tests to:
- Check for `LevelCompletedLog` event (in utils)
- Remove 'VM Exception ...' message to improve test readability
I tested the new filter locally with a sample contract and a local Geth development node, to reproduce real conditions as close as possible, and the new filter should work as expected. This hot fix prevent further mismatches in completed levels when syncing player progress.
=> Fix event filtering when syncing player progress

gamedata/descriptions/levels/elevator_complete.md
Issue #155.
Advice has been updated as view and pure functions will now prevent state modifications with the use of STATICCALL.
=> Updates view modifier advice

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json, src/index.js, src/middlewares/setNetwork.js, src/utils/ethutil.js
Resolves https://github.com/OpenZeppelin/ethernaut/issues/198 
Resolves https://github.com/OpenZeppelin/ethernaut/issues/200 
and partially https://github.com/OpenZeppelin/ethernaut/issues/188
=> Refactor for latest Metamask changes

gamedata/descriptions/levels/force_complete.md
See #209
`this.balance` is deprecated since Solidity 0.5.0 and replaced with `address(this).balance`
[From the Docs](https://docs.soliditylang.org/en/v0.8.3/units-and-global-variables.html#members-of-address-types)
=> chore: updating for solidity > 0.5.0

gamedata/descriptions/levels/gatekeeper1.md
• `msg.gas` is deprecated since solidity 0.4.21
• the links to docs are being redirected to `soliditylang.org`
• updated docs version to `stable` (that might be controversial – please amend)
=> Update hints for Gatekeeper 1

contracts/levels/AlienCodex.sol, contracts/levels/CoinFlip.sol, contracts/levels/Delegation.sol, contracts/levels/Denial.sol, contracts/levels/Dex.sol, contracts/levels/Dummy.sol, contracts/levels/DummyLevel.sol, contracts/levels/Elevator.sol, contracts/levels/Fallback.sol, contracts/levels/Fallout.sol, contracts/levels/Force.sol, contracts/levels/GatekeeperOne.sol, contracts/levels/GatekeeperTwo.sol, contracts/levels/Instance.sol, contracts/levels/King.sol, contracts/levels/MagicNum.sol, contracts/levels/NaughtCoin.sol, contracts/levels/Preservation.sol, contracts/levels/Privacy.sol, contracts/levels/Recovery.sol, contracts/levels/RecoverySimpleToken.sol, contracts/levels/Reentrance.sol, contracts/levels/Shop.sol, contracts/levels/Telephone.sol, contracts/levels/Token.sol, contracts/levels/Vault.sol
Remix pushes a warning on compilation every time SPDX is not present, so hopefully this will make debugging much more cleaner and pleasant for future people taking on the challenge
(original PR was [this](https://github.com/OpenZeppelin/ethernaut/pull/219), but messed up the whole rebase/merge and had to create a new PR)
=> Adding SPDX licenses (MIT)

client/public/index.html, client/src/styles/app.css, client/src/styles/footer-level.css, client/src/styles/hubspot.css
HubSpot Tracking code has been added to the project in order to be able to define HubSpot Popup forms on the website. 
A new stylesheet at the footer level is also added in order to override some keyframe rules placed by HubSpot.
=> Add HubSpot Tracking code into the project and turn the default animation for HS banners

client/src/gamedata/en/descriptions/levels/king_complete.md
Fixed misspelling of "oversimplified" and "happened", combined sentence fragment with previous sentence, and removed unnecessary newlines.
=> Fix typos/fragment in completion page after King

client/src/containers/Level.js, client/src/styles/app.css, client/src/styles/level.css
Remove scaling down of level UI. This scaling results in the use of only 60% of the screen. Typically, this would not be much of an issue. However, the fact that this site is used with console open, leaves the user (assuming they use a horizontal console) with much less used screen space. This results in the need to unnecessarily scroll to view the source code. This PR mitigates that by statically sizing the level ui to 800px
.
=> Remove Level UI Scaling

yarn.lock
1. Upgraded cross-fetch from 2.2.3 to 2.2.6
2. Upgraded minimist from 1.2.5 to 1.2.7
We can close PRs 
1. #414 
2. #376
=> Upgraded cross-fetch and minimist (Dependabot updates)

client/src/gamedata/en/descriptions/levels/dex2.md
Remove the second hint bullet point (which makes the level too easy!)
Once one realizes that any token can be used, the problem is trivial even without price manipulation. But it isn't necessary to explicitly inform players that a custom token could be used -- if the player follows the first bit of advice and does a diff between the two, they will discover that the first `require` statement (which checks if the token is a valid one) has been removed. It's not a big leap from there to realize how introducing one or two additional tokens could work. In fact, the new tokens don't even need to be modified from the given `SwappableToken` -- all one needs to do is transfer 1 token to the dex after creating the token, such that swapping from 1 of the new token to either of the original tokens …
=> Update dex2.md (remove second hint, which makes the level too easy)

contracts/contracts/levels/RecoveryFactory.sol
Currently the Factory contract of the Recovery level attempts to send a hardcoded 0.001 ether to the "lost" `SimpleToken` instance for recovery.
This has the following issues:
1. If the user sets a msg.value of <0.001 ether and there are no other funds in the factory contract the level creation transaction will fail without revert reason.
2. If the user sets a msg.value >0.001 ether the excess amount will be "stuck" in the factory contract and not be recovered upon solving the level
3. If another user had previously committed the mistake outlined in 2. a third user can come along and obtain those left over funds by creating a level with msg.value < 0.001 ether
This PR fixes that by replacing the current logic in the Recovery factory with what is "standard" in the other level factories …
=> Fix ether value pass through in Recovery factory

client/src/gamedata/en/descriptions/levels/recovery_complete.md
the old link already dead, so we need to change to the new link
=> Fix dead link in recovery complete level

contracts/contracts/attacks/ReentranceAttack.sol, contracts/contracts/levels/Reentrance.sol
Solidity 0.6.4 and call{value: ...}() instead of call.value()()
=> compile version error!

client/src/middlewares/loadEthernautContract.js, client/src/utils/deploycontract.js
- Logs the contract names while they are deployed.
- Fix the `Ethernaut not found` error when refreshing the level page.
=> Deployment logger

client/scripts/deploy_contracts.mjs, client/src/utils/ethutil.js
I've changed the gas limit to 30000000 and also change the imports in `ethutil.js` to
```js
import * as constants from "../constants.js";
import { NETWORKS_INGAME } from '../constants.js'
```
=> Deploy problem solved

client/src/containers/Level.js
I was going through Ethernaut and experienced some problems with the dropdown behavior, that is, immediate close on mouse leaving the dropdown.
This PR aims to:
- give a better experience to users on higher DPI monitors
- better support for non-standard pointing devices
- overall improve accessibility by giving the dropdown an expected behavior
Changes:
- removed `onMouseLeave`
- added a `onClickOutside` behavior to the close the dropdown on clicks outside `level-selector-nav` div
- removed `onClick={this.closeDropdown}` from `<main>`, this is completely replaced by the `onClickOutside` behavior
I suppose this was done to account for mobile devices, but two considerations have to be made:
- The whole experience is not engineered for mobile users
- this change maintains previous mobile …
=> UX Enhancement, Level Dropdown Behavior, remove onMouseLeave

client/src/gamedata/en/descriptions/levels/dex_complete.md, client/src/gamedata/es/descriptions/levels/dex_complete.md, client/src/gamedata/ja/descriptions/levels/dex_complete.md, client/src/gamedata/ru/descriptions/levels/dex_complete.md, client/src/gamedata/zh_cn/descriptions/levels/dex_complete.md
Solves https://github.com/OpenZeppelin/ethernaut/issues/631
- Fixed, rephrased, and slightly expanded for en and es.
- jap and ru links fixed but text is outdated.
- It seems that the zh_cn text is outdated.
=> Fix links, and lightly rephrase dex_complete.md

client/src/gamedata/en/descriptions/levels/stake.md
Maybe the smallest PR ever seen to fix this tiny typo on the new level 31 - Stake.
The English description was edited as follows:
```diff
- You staked balance must be 0.
+ Your staked balance must be 0.
```
And... that's it!
=> 📝 (stake.md): Fix typo in Stake level description

client/package.json
- closes: https://github.com/OpenZeppelin/ethernaut/issues/736
=> :hammer: Fix `@truffle/contract` dependency to `4.6.6` 

client/src/gamedata/en/descriptions/levels/stake.md
This change has been done to update the previous link as the ERC20 specification has been moved which has been mentioned in the [previous link](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md).
Thus, the user won't need to reach the exact link using 2 clicks instead of 1
Thanks!
=> Fixed Link

client/src/gamedata/en/descriptions/levels/magicnum.md, client/src/gamedata/es/descriptions/levels/magicnum.md, client/src/gamedata/fr/descriptions/levels/magicnum.md, client/src/gamedata/pt_br/descriptions/levels/magicnum.md, contracts/src/levels/MagicNumFactory.sol
**Two changes were made to the Magic Number level description:**
1. `10 opcodes` was replaced with `10 bytes` because the level checks the code length in bytes, not the number of opcodes.
2. The length of the expected response (32 bytes) was added since it's not immediately clear how many bytes the contract should return.
=> text(MagicNum): improve level description

client/src/containers/Level.js, client/src/index.js
When web3 provider is present but locked (Metamask not logged in for example), and loading directly a level URL without passing through the homepage, produced a 404 due to missing gamedata in the store. 
Forcing to load game data now.
=> Missing gamedata

client/scripts/docs/supersede_level.md, client/src/gamedata/en/descriptions/levels/dex2.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "mainet" to "mainnet".
Corrected "revet" to "revert".
Corrected "subtlely" to "subtly".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files
